### ISSUE TITLE
Opening a safed project fails sometimes

### ISSUE THREAD

**Issue by timmartinberger** [luhsra/MinimaxSimulator#40]
We are unable to reopen a project we were recently working on.

An error message appears when we attempt to open such a project:
"Die angegebene Datei ist beschädigt oder kein gültiges Projekt".

**Comment by prohde** [comment]
Could you please share the project you are trying to reopen or steps to reproduce the issue?
Personally, so far, I only encountered this issue when using different versions of the application.

**Comment by timmartinberger** [comment]
[minmax.zip](https://github.com/luhsra/MinimaxSimulator/files/5495027/minmax.zip)
It is this project. Another issue was the simulator to crash suddenly during working on a project.
We suppose it is the same reason as the case that we can't open it.

**Comment by dkiechle** [comment]
That problem is already known.
It always occurs if there is only one value in a row of the control signal table when saving. On JSON export only a single element but no containing array is written for this row, but importing the JSON always requires an array. The error must be corrected manually in the JSON file and then the project can be imported again.
